[2023-06-29 11:26:43,153][MainThread:1320][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 11:27:37,770][Thread-1:13392][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 65, in screenshot
    screenshot_bytes = await page.screenshot(f"{BASE_DIR}/{time.time()}.png")
TypeError: screenshot() takes 1 positional argument but 2 were given
[2023-06-29 11:27:37,770][Thread-1:13392][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 65, in screenshot
    screenshot_bytes = await page.screenshot(f"{BASE_DIR}/{time.time()}.png")
TypeError: screenshot() takes 1 positional argument but 2 were given
[2023-06-29 11:27:51,707][MainThread:1320][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-29 11:27:52,318][MainThread:14608][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 11:28:40,023][Thread-1:14856][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: net::ERR_EMPTY_RESPONSE at https://www.facebook.com/search/top/?q=75J7RQFX
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-29 11:28:40,023][Thread-1:14856][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: net::ERR_EMPTY_RESPONSE at https://www.facebook.com/search/top/?q=75J7RQFX
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-29 12:41:57,988][Thread-1:14856][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-29 12:41:57,988][Thread-1:14856][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-29 12:42:57,887][Thread-1:14856][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-29 12:42:57,887][Thread-1:14856][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-29 12:58:53,077][MainThread:14608][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-29 12:58:54,008][MainThread:1996][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 12:59:36,762][MainThread:1996][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-29 12:59:37,303][MainThread:13376][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 13:00:44,967][MainThread:13376][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-29 13:00:45,629][MainThread:2200][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 13:00:53,534][Thread-1:17540][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: net::ERR_PROXY_CONNECTION_FAILED at https://www.facebook.com/search/top/?q=75J7RQFX
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-29 13:00:53,534][Thread-1:17540][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: net::ERR_PROXY_CONNECTION_FAILED at https://www.facebook.com/search/top/?q=75J7RQFX
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-29 13:07:19,848][MainThread:2200][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-29 13:07:20,463][MainThread:14516][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 13:12:53,318][MainThread:14516][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-29 13:12:53,883][MainThread:18748][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 14:02:10,798][MainThread:18748][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-29 14:02:11,263][MainThread:19964][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 14:04:09,760][MainThread:19964][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-29 14:04:10,226][MainThread:20516][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 14:04:33,988][Thread-1:20852][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 80, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: net::ERR_EMPTY_RESPONSE at https://www.facebook.com/search/top/?q=75J7RQFX
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-29 14:04:33,988][Thread-1:20852][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 80, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: net::ERR_EMPTY_RESPONSE at https://www.facebook.com/search/top/?q=75J7RQFX
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-29 14:19:14,719][MainThread:20516][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-29 14:19:15,263][MainThread:16180][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 14:19:34,084][Thread-1:19624][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 82, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Navigation failed because page was closed!
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-29 14:19:34,084][Thread-1:19624][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 82, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Navigation failed because page was closed!
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-29 14:19:40,801][MainThread:16180][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-29 14:19:41,785][MainThread:14568][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 14:23:34,293][MainThread:14568][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-29 14:23:35,024][MainThread:17900][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 14:28:02,178][MainThread:17900][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-29 14:28:03,233][MainThread:14520][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 14:29:12,195][Thread-1:20080][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 82, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 65, in screenshot
    await page.wait_for_timeout(5000)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 11680, in wait_for_timeout
    await self._impl_obj.wait_for_timeout(timeout=timeout)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 956, in wait_for_timeout
    await self._main_frame.wait_for_timeout(timeout)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 757, in wait_for_timeout
    await self._channel.send("waitForTimeout", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
[2023-06-29 14:29:12,195][Thread-1:20080][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 82, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 65, in screenshot
    await page.wait_for_timeout(5000)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 11680, in wait_for_timeout
    await self._impl_obj.wait_for_timeout(timeout=timeout)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 956, in wait_for_timeout
    await self._main_frame.wait_for_timeout(timeout)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 757, in wait_for_timeout
    await self._channel.send("waitForTimeout", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
[2023-06-29 14:31:41,992][MainThread:14520][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-29 14:31:43,115][MainThread:20956][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 14:31:48,605][Thread-1:17660][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 82, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 37, in screenshot
    page = await context.new_page(viewport={"width": 1920, "height": 1080})
TypeError: new_page() got an unexpected keyword argument 'viewport'
[2023-06-29 14:31:48,605][Thread-1:17660][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 82, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 37, in screenshot
    page = await context.new_page(viewport={"width": 1920, "height": 1080})
TypeError: new_page() got an unexpected keyword argument 'viewport'
[2023-06-29 14:33:03,427][MainThread:20956][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-29 14:33:04,202][MainThread:18924][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 14:33:47,192][Thread-1:19564][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 82, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-29 14:33:47,192][Thread-1:19564][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 82, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-29 14:34:35,406][MainThread:18924][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-29 14:34:36,755][MainThread:18108][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 14:34:43,484][MainThread:18108][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-29 14:34:44,221][MainThread:18088][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 14:51:47,746][MainThread:18088][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-29 14:51:48,674][MainThread:18032][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 14:52:41,300][MainThread:18032][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-29 14:52:42,179][MainThread:13436][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 14:53:01,895][MainThread:13436][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-29 14:53:02,783][MainThread:876][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 14:56:01,325][MainThread:876][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-29 14:56:02,003][MainThread:18084][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 15:06:07,606][MainThread:18084][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-29 15:06:08,538][MainThread:9392][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 15:17:35,758][MainThread:21076][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 15:19:49,343][MainThread:21076][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\AutoTestCode\settings.py changed, reloading.]
[2023-06-29 15:19:50,227][MainThread:16972][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 15:21:08,569][MainThread:16972][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\AutoTestCode\settings.py changed, reloading.]
[2023-06-29 15:21:09,309][MainThread:8552][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 15:23:57,490][MainThread:8552][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\AutoTestCode\settings.py changed, reloading.]
[2023-06-29 15:23:58,294][MainThread:8804][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 15:24:22,441][MainThread:20372][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 15:24:35,966][Thread-1:21068][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 76, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: net::ERR_PROXY_CONNECTION_FAILED at https://www.facebook.com/search/top/?q=75J7RQFX
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-29 15:24:35,966][Thread-1:21068][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 76, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: net::ERR_PROXY_CONNECTION_FAILED at https://www.facebook.com/search/top/?q=75J7RQFX
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-29 15:25:54,942][MainThread:20372][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\AutoTestCode\settings.py changed, reloading.]
[2023-06-29 15:25:55,950][MainThread:13340][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 15:26:10,046][Thread-1:20724][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 76, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: net::ERR_PROXY_CONNECTION_FAILED at https://www.facebook.com/search/top/?q=75J7RQFX
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-29 15:26:10,046][Thread-1:20724][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 76, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: net::ERR_PROXY_CONNECTION_FAILED at https://www.facebook.com/search/top/?q=75J7RQFX
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-29 15:26:52,831][MainThread:13340][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\AutoTestCode\settings.py changed, reloading.]
[2023-06-29 15:26:53,785][MainThread:19728][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 15:27:02,286][Thread-1:18912][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 76, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: net::ERR_PROXY_CONNECTION_FAILED at https://www.facebook.com/search/top/?q=75J7RQFX
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-29 15:27:02,286][Thread-1:18912][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 76, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: net::ERR_PROXY_CONNECTION_FAILED at https://www.facebook.com/search/top/?q=75J7RQFX
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-29 15:28:15,235][MainThread:19728][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\AutoTestCode\settings.py changed, reloading.]
[2023-06-29 15:28:16,017][MainThread:19904][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 15:29:06,164][Thread-1:20032][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 76, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-29 15:29:06,164][Thread-1:20032][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 76, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-29 15:48:22,521][MainThread:19904][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-29 15:48:23,382][MainThread:20288][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 15:48:49,888][Thread-1:22196][task_id:django.request][log.py:241][WARNING][Method Not Allowed: /facebookWebsite/facebook]
[2023-06-29 15:51:41,356][MainThread:20288][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-29 15:51:42,471][MainThread:21064][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 15:52:27,066][Thread-1:15920][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 16, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 76, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=None", waiting until "load"
============================================================
[2023-06-29 15:52:27,066][Thread-1:15920][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 16, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 76, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=None", waiting until "load"
============================================================
[2023-06-29 15:53:27,317][Thread-1:15920][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 16, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 76, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-29 15:53:27,317][Thread-1:15920][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 16, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 76, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-29 15:55:27,674][MainThread:21064][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-29 15:55:28,635][MainThread:4228][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 15:57:12,691][MainThread:4228][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-29 15:57:13,508][MainThread:22404][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 15:57:32,072][Thread-1:15096][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 76, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: net::ERR_PROXY_CONNECTION_FAILED at https://www.facebook.com/search/top/?q=75J7RQFX
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-29 15:57:32,072][Thread-1:15096][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 76, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: net::ERR_PROXY_CONNECTION_FAILED at https://www.facebook.com/search/top/?q=75J7RQFX
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-29 15:57:51,623][MainThread:22404][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-29 15:57:52,371][MainThread:20500][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 16:07:33,654][MainThread:20500][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-29 16:07:34,637][MainThread:18232][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 16:43:59,515][Thread-1:8556][task_id:django.request][log.py:241][WARNING][Method Not Allowed: /facebookWebsite/facebook]
[2023-06-29 16:44:18,076][Thread-2:22104][task_id:django.request][log.py:241][WARNING][Method Not Allowed: /facebookWebsite/facebook]
[2023-06-29 16:47:55,600][Thread-3:22120][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 17, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 76, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 48, in screenshot
    while await page.locator("a", has_text="了解更多").is_visible() is False:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17082, in is_visible
    return mapping.from_maybe_impl(await self._impl_obj.is_visible(timeout=timeout))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 492, in is_visible
    return await self._frame.is_visible(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 353, in is_visible
    return await self._channel.send("isVisible", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target crashed
=========================== logs ===========================
  checking visibility of locator("a").filter(has_text="了解更多")
============================================================
[2023-06-29 16:47:55,600][Thread-3:22120][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 17, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 76, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 48, in screenshot
    while await page.locator("a", has_text="了解更多").is_visible() is False:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17082, in is_visible
    return mapping.from_maybe_impl(await self._impl_obj.is_visible(timeout=timeout))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 492, in is_visible
    return await self._frame.is_visible(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 353, in is_visible
    return await self._channel.send("isVisible", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target crashed
=========================== logs ===========================
  checking visibility of locator("a").filter(has_text="了解更多")
============================================================
[2023-06-29 16:47:55,842][Thread-4:10372][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 17, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 76, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 48, in screenshot
    while await page.locator("a", has_text="了解更多").is_visible() is False:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17082, in is_visible
    return mapping.from_maybe_impl(await self._impl_obj.is_visible(timeout=timeout))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 492, in is_visible
    return await self._frame.is_visible(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 353, in is_visible
    return await self._channel.send("isVisible", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target crashed
=========================== logs ===========================
  checking visibility of locator("a").filter(has_text="了解更多")
============================================================
[2023-06-29 16:47:55,842][Thread-4:10372][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 17, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 76, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 48, in screenshot
    while await page.locator("a", has_text="了解更多").is_visible() is False:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17082, in is_visible
    return mapping.from_maybe_impl(await self._impl_obj.is_visible(timeout=timeout))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 492, in is_visible
    return await self._frame.is_visible(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 353, in is_visible
    return await self._channel.send("isVisible", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target crashed
=========================== logs ===========================
  checking visibility of locator("a").filter(has_text="了解更多")
============================================================
[2023-06-29 16:48:11,742][Thread-8:23512][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 17, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 76, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 48, in screenshot
    while await page.locator("a", has_text="了解更多").is_visible() is False:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17082, in is_visible
    return mapping.from_maybe_impl(await self._impl_obj.is_visible(timeout=timeout))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 492, in is_visible
    return await self._frame.is_visible(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 353, in is_visible
    return await self._channel.send("isVisible", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target crashed
=========================== logs ===========================
  checking visibility of locator("a").filter(has_text="了解更多")
============================================================
[2023-06-29 16:48:11,742][Thread-8:23512][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 17, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 76, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 48, in screenshot
    while await page.locator("a", has_text="了解更多").is_visible() is False:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17082, in is_visible
    return mapping.from_maybe_impl(await self._impl_obj.is_visible(timeout=timeout))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 492, in is_visible
    return await self._frame.is_visible(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 353, in is_visible
    return await self._channel.send("isVisible", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target crashed
=========================== logs ===========================
  checking visibility of locator("a").filter(has_text="了解更多")
============================================================
[2023-06-29 16:48:13,971][Thread-9:22084][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 17, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 76, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 48, in screenshot
    while await page.locator("a", has_text="了解更多").is_visible() is False:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17082, in is_visible
    return mapping.from_maybe_impl(await self._impl_obj.is_visible(timeout=timeout))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 492, in is_visible
    return await self._frame.is_visible(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 353, in is_visible
    return await self._channel.send("isVisible", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target crashed
=========================== logs ===========================
  checking visibility of locator("a").filter(has_text="了解更多")
============================================================
[2023-06-29 16:48:13,971][Thread-9:22084][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 17, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 76, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 48, in screenshot
    while await page.locator("a", has_text="了解更多").is_visible() is False:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17082, in is_visible
    return mapping.from_maybe_impl(await self._impl_obj.is_visible(timeout=timeout))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 492, in is_visible
    return await self._frame.is_visible(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 353, in is_visible
    return await self._channel.send("isVisible", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target crashed
=========================== logs ===========================
  checking visibility of locator("a").filter(has_text="了解更多")
============================================================
[2023-06-29 16:48:27,123][Thread-7:23504][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 17, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 76, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 48, in screenshot
    while await page.locator("a", has_text="了解更多").is_visible() is False:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17082, in is_visible
    return mapping.from_maybe_impl(await self._impl_obj.is_visible(timeout=timeout))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 492, in is_visible
    return await self._frame.is_visible(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 353, in is_visible
    return await self._channel.send("isVisible", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target crashed
=========================== logs ===========================
  checking visibility of locator("a").filter(has_text="了解更多")
============================================================
[2023-06-29 16:48:27,123][Thread-7:23504][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 17, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 76, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 48, in screenshot
    while await page.locator("a", has_text="了解更多").is_visible() is False:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17082, in is_visible
    return mapping.from_maybe_impl(await self._impl_obj.is_visible(timeout=timeout))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 492, in is_visible
    return await self._frame.is_visible(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 353, in is_visible
    return await self._channel.send("isVisible", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target crashed
=========================== logs ===========================
  checking visibility of locator("a").filter(has_text="了解更多")
============================================================
[2023-06-29 16:56:31,178][MainThread:18232][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-29 16:56:31,998][MainThread:8804][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 17:03:24,103][MainThread:8804][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-29 17:03:24,957][MainThread:25348][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 17:06:49,710][MainThread:25376][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 17:07:38,023][Thread-1:19656][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 17, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 79, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=21", waiting until "load"
============================================================
[2023-06-29 17:07:38,023][Thread-1:19656][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 17, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 79, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=21", waiting until "load"
============================================================
[2023-06-29 17:08:59,834][Thread-3:3548][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 17, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 79, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 50, in screenshot
    while await page.locator("a", has_text="了解更多").is_visible() is False:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17082, in is_visible
    return mapping.from_maybe_impl(await self._impl_obj.is_visible(timeout=timeout))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 492, in is_visible
    return await self._frame.is_visible(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 353, in is_visible
    return await self._channel.send("isVisible", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
[2023-06-29 17:08:59,834][Thread-3:3548][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 17, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 79, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 50, in screenshot
    while await page.locator("a", has_text="了解更多").is_visible() is False:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17082, in is_visible
    return mapping.from_maybe_impl(await self._impl_obj.is_visible(timeout=timeout))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 492, in is_visible
    return await self._frame.is_visible(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 353, in is_visible
    return await self._channel.send("isVisible", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
[2023-06-29 17:13:46,933][MainThread:24264][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 17:15:28,922][Thread-2:3548][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 17, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 79, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 50, in screenshot
    while await page.locator("a", has_text="了解更多").is_visible() is False:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17082, in is_visible
    return mapping.from_maybe_impl(await self._impl_obj.is_visible(timeout=timeout))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 492, in is_visible
    return await self._frame.is_visible(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 353, in is_visible
    return await self._channel.send("isVisible", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
[2023-06-29 17:15:28,922][Thread-2:3548][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 17, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 79, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 50, in screenshot
    while await page.locator("a", has_text="了解更多").is_visible() is False:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17082, in is_visible
    return mapping.from_maybe_impl(await self._impl_obj.is_visible(timeout=timeout))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 492, in is_visible
    return await self._frame.is_visible(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 353, in is_visible
    return await self._channel.send("isVisible", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
[2023-06-29 17:16:17,204][MainThread:19744][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 17:30:24,045][MainThread:21144][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 17:34:46,961][MainThread:21144][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-29 17:34:47,466][MainThread:17284][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 17:36:01,503][Thread-1:20468][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 17, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 79, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-29 17:36:01,503][Thread-1:20468][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 17, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 79, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-29 17:40:59,092][MainThread:17284][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-29 17:40:59,667][MainThread:5764][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 17:48:32,031][MainThread:5764][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-29 17:48:33,096][MainThread:22876][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 17:49:37,226][MainThread:22876][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-29 17:49:37,947][MainThread:20988][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 17:54:30,447][MainThread:20988][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-29 17:54:30,984][MainThread:23132][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-29 18:00:53,317][Thread-3:21796][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 19, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 64, in screenshot
    screenshot_bytes = await i.screenshot()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17240, in screenshot
    await self._impl_obj.screenshot(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 521, in screenshot
    return await self._with_element(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 119, in _with_element
    return await task(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_element_handle.py", line 306, in screenshot
    encoded_binary = await self._channel.send("screenshot", params)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 29984ms exceeded.
=========================== logs ===========================
taking element screenshot
  waiting for element to be visible and stable
  element is visible and stable
============================================================
[2023-06-29 18:00:53,317][Thread-3:21796][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 19, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 64, in screenshot
    screenshot_bytes = await i.screenshot()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17240, in screenshot
    await self._impl_obj.screenshot(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 521, in screenshot
    return await self._with_element(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 119, in _with_element
    return await task(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_element_handle.py", line 306, in screenshot
    encoded_binary = await self._channel.send("screenshot", params)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 29984ms exceeded.
=========================== logs ===========================
taking element screenshot
  waiting for element to be visible and stable
  element is visible and stable
============================================================
[2023-06-30 09:09:55,305][MainThread:23132][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
