[2023-06-30 09:09:56,103][MainThread:25316][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 09:21:57,864][Thread-1:21820][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 19, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: net::ERR_PROXY_CONNECTION_FAILED at https://www.facebook.com/search/top/?q=75J7RQFX
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-30 09:21:57,864][Thread-1:21820][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 19, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: net::ERR_PROXY_CONNECTION_FAILED at https://www.facebook.com/search/top/?q=75J7RQFX
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-30 09:29:50,506][MainThread:25316][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-30 09:29:51,035][MainThread:22384][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 09:30:09,809][MainThread:22384][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-30 09:30:10,386][MainThread:24548][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 09:32:35,441][MainThread:24548][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-30 09:32:36,017][MainThread:20288][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 09:35:44,131][Thread-1:7488][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 18, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 80, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 52, in screenshot
    await page.mouse.wheel(0, 100)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 1519, in wheel
    await self._impl_obj.wheel(deltaX=delta_x, deltaY=delta_y)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_input.py", line 84, in wheel
    await self._channel.send("mouseWheel", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target closed
[2023-06-30 09:35:44,131][Thread-1:7488][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 18, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 80, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 52, in screenshot
    await page.mouse.wheel(0, 100)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 1519, in wheel
    await self._impl_obj.wheel(deltaX=delta_x, deltaY=delta_y)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_input.py", line 84, in wheel
    await self._channel.send("mouseWheel", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target closed
[2023-06-30 09:37:32,508][MainThread:16868][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 09:40:22,727][Thread-4:14912][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 18, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 80, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 63, in screenshot
    screenshot_bytes = await i.screenshot()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17240, in screenshot
    await self._impl_obj.screenshot(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 521, in screenshot
    return await self._with_element(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 119, in _with_element
    return await task(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_element_handle.py", line 306, in screenshot
    encoded_binary = await self._channel.send("screenshot", params)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 29969ms exceeded.
=========================== logs ===========================
taking element screenshot
  waiting for element to be visible and stable
  element is visible and stable
============================================================
[2023-06-30 09:40:22,727][Thread-4:14912][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 18, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 80, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 63, in screenshot
    screenshot_bytes = await i.screenshot()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17240, in screenshot
    await self._impl_obj.screenshot(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 521, in screenshot
    return await self._with_element(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 119, in _with_element
    return await task(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_element_handle.py", line 306, in screenshot
    encoded_binary = await self._channel.send("screenshot", params)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 29969ms exceeded.
=========================== logs ===========================
taking element screenshot
  waiting for element to be visible and stable
  element is visible and stable
============================================================
[2023-06-30 09:46:31,041][Thread-11:22816][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 18, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 80, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 51, in screenshot
    while await page.locator("a", has_text="了解更多").is_visible(timeout=3000) is False:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17082, in is_visible
    return mapping.from_maybe_impl(await self._impl_obj.is_visible(timeout=timeout))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 492, in is_visible
    return await self._frame.is_visible(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 353, in is_visible
    return await self._channel.send("isVisible", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Execution context was destroyed, most likely because of a navigation
=========================== logs ===========================
  checking visibility of locator("a").filter(has_text="了解更多")
============================================================
[2023-06-30 09:46:31,041][Thread-11:22816][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 18, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 80, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 51, in screenshot
    while await page.locator("a", has_text="了解更多").is_visible(timeout=3000) is False:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17082, in is_visible
    return mapping.from_maybe_impl(await self._impl_obj.is_visible(timeout=timeout))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 492, in is_visible
    return await self._frame.is_visible(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 353, in is_visible
    return await self._channel.send("isVisible", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Execution context was destroyed, most likely because of a navigation
=========================== logs ===========================
  checking visibility of locator("a").filter(has_text="了解更多")
============================================================
[2023-06-30 09:57:32,307][MainThread:5060][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 09:58:31,491][Thread-3:1548][task_id:django.request][log.py:241][WARNING][Not Found: /ui]
[2023-06-30 09:58:32,100][Thread-3:1548][task_id:django.request][log.py:241][WARNING][Not Found: /favicon.ico]
[2023-06-30 10:02:52,031][MainThread:5060][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-30 10:02:52,591][MainThread:24144][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 10:10:35,667][MainThread:24144][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-30 10:10:36,316][MainThread:22140][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 10:13:06,420][MainThread:22140][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-30 10:13:06,976][MainThread:20504][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 10:15:35,277][Thread-2:25388][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 19, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 64, in screenshot
    screenshot_bytes = await i.screenshot()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17240, in screenshot
    await self._impl_obj.screenshot(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 521, in screenshot
    return await self._with_element(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 119, in _with_element
    return await task(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_element_handle.py", line 306, in screenshot
    encoded_binary = await self._channel.send("screenshot", params)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 29984ms exceeded.
=========================== logs ===========================
taking element screenshot
  waiting for element to be visible and stable
  element is visible and stable
============================================================
[2023-06-30 10:15:35,277][Thread-2:25388][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 19, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 64, in screenshot
    screenshot_bytes = await i.screenshot()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17240, in screenshot
    await self._impl_obj.screenshot(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 521, in screenshot
    return await self._with_element(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 119, in _with_element
    return await task(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_element_handle.py", line 306, in screenshot
    encoded_binary = await self._channel.send("screenshot", params)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 29984ms exceeded.
=========================== logs ===========================
taking element screenshot
  waiting for element to be visible and stable
  element is visible and stable
============================================================
[2023-06-30 10:20:21,573][Thread-5:10468][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 19, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 64, in screenshot
    screenshot_bytes = await i.screenshot()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17240, in screenshot
    await self._impl_obj.screenshot(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 521, in screenshot
    return await self._with_element(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 119, in _with_element
    return await task(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_element_handle.py", line 306, in screenshot
    encoded_binary = await self._channel.send("screenshot", params)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 29969ms exceeded.
=========================== logs ===========================
taking element screenshot
  waiting for element to be visible and stable
  element is visible and stable
============================================================
[2023-06-30 10:20:21,573][Thread-5:10468][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 19, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 64, in screenshot
    screenshot_bytes = await i.screenshot()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17240, in screenshot
    await self._impl_obj.screenshot(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 521, in screenshot
    return await self._with_element(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 119, in _with_element
    return await task(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_element_handle.py", line 306, in screenshot
    encoded_binary = await self._channel.send("screenshot", params)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 29969ms exceeded.
=========================== logs ===========================
taking element screenshot
  waiting for element to be visible and stable
  element is visible and stable
============================================================
[2023-06-30 10:21:13,816][MainThread:22692][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 10:22:50,006][MainThread:24528][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 10:32:09,337][Thread-15:21268][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 19, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 64, in screenshot
    screenshot_bytes = await i.screenshot()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17240, in screenshot
    await self._impl_obj.screenshot(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 521, in screenshot
    return await self._with_element(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 119, in _with_element
    return await task(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_element_handle.py", line 306, in screenshot
    encoded_binary = await self._channel.send("screenshot", params)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 29969ms exceeded.
=========================== logs ===========================
taking element screenshot
  waiting for element to be visible and stable
  element is visible and stable
============================================================
[2023-06-30 10:32:09,337][Thread-15:21268][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 19, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 64, in screenshot
    screenshot_bytes = await i.screenshot()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17240, in screenshot
    await self._impl_obj.screenshot(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 521, in screenshot
    return await self._with_element(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 119, in _with_element
    return await task(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_element_handle.py", line 306, in screenshot
    encoded_binary = await self._channel.send("screenshot", params)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 29969ms exceeded.
=========================== logs ===========================
taking element screenshot
  waiting for element to be visible and stable
  element is visible and stable
============================================================
[2023-06-30 10:33:01,792][MainThread:24528][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-30 10:33:02,337][MainThread:21668][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 10:35:23,805][Thread-8:21092][task_id:django.request][log.py:241][WARNING][Not Found: /favicon.ico]
[2023-06-30 10:53:57,183][MainThread:15476][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 10:54:09,500][Thread-3:12564][task_id:django.request][log.py:241][WARNING][Method Not Allowed: /facebookWebsite/facebook]
[2023-06-30 10:54:46,614][MainThread:15476][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-30 10:54:47,145][MainThread:19000][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 10:57:16,881][Thread-11:22596][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 19, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 64, in screenshot
    screenshot_bytes = await i.screenshot()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17240, in screenshot
    await self._impl_obj.screenshot(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 521, in screenshot
    return await self._with_element(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 119, in _with_element
    return await task(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_element_handle.py", line 306, in screenshot
    encoded_binary = await self._channel.send("screenshot", params)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 29969ms exceeded.
=========================== logs ===========================
taking element screenshot
  waiting for element to be visible and stable
  element is visible and stable
============================================================
[2023-06-30 10:57:16,881][Thread-11:22596][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 19, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 64, in screenshot
    screenshot_bytes = await i.screenshot()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17240, in screenshot
    await self._impl_obj.screenshot(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 521, in screenshot
    return await self._with_element(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 119, in _with_element
    return await task(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_element_handle.py", line 306, in screenshot
    encoded_binary = await self._channel.send("screenshot", params)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 29969ms exceeded.
=========================== logs ===========================
taking element screenshot
  waiting for element to be visible and stable
  element is visible and stable
============================================================
[2023-06-30 11:09:06,325][Thread-113:25992][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 19, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-30 11:09:06,325][Thread-113:25992][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 19, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-30 11:13:41,846][Thread-137:15120][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 19, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-30 11:13:41,846][Thread-137:15120][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 19, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-30 11:16:22,254][MainThread:26120][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 11:17:03,747][Thread-2:25312][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 19, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 80, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 53, in screenshot
    if await page.get_by_text("展开").count() > 0:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 16661, in count
    return mapping.from_maybe_impl(await self._impl_obj.count())
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 384, in count
    return await self._frame._query_count(self._selector)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 131, in _query_count
    return await self._channel.send("queryCount", {"selector": selector})
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Execution context was destroyed, most likely because of a navigation
[2023-06-30 11:17:03,747][Thread-2:25312][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 19, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 80, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 53, in screenshot
    if await page.get_by_text("展开").count() > 0:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 16661, in count
    return mapping.from_maybe_impl(await self._impl_obj.count())
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 384, in count
    return await self._frame._query_count(self._selector)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 131, in _query_count
    return await self._channel.send("queryCount", {"selector": selector})
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Execution context was destroyed, most likely because of a navigation
[2023-06-30 11:24:38,472][Thread-28:22872][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:24:48,153][Thread-30:22972][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:24:58,372][Thread-32:19304][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:25:18,509][Thread-34:25608][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:25:48,188][Thread-36:16700][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:25:58,213][Thread-38:18824][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:26:08,189][Thread-40:24452][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:26:28,313][Thread-42:17092][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:26:38,398][Thread-44:7468][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:27:17,101][Thread-46:2996][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:27:27,832][Thread-48:23400][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:27:37,268][Thread-50:21828][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:27:47,108][Thread-52:13664][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:28:08,234][Thread-54:22992][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:28:17,199][Thread-56:12456][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:28:37,538][Thread-58:26352][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:29:26,209][Thread-60:24876][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:29:36,268][Thread-62:20252][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:29:56,100][Thread-65:25244][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:30:12,950][Thread-68:7932][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:30:23,068][Thread-70:13676][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:30:32,958][Thread-72:23488][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:30:52,991][Thread-74:14300][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:31:02,981][Thread-76:24032][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:31:13,515][Thread-78:14108][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:31:22,975][Thread-80:5452][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:31:33,178][Thread-82:16932][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:31:53,341][Thread-84:20428][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:32:03,035][Thread-86:22760][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:32:13,248][Thread-88:416][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:32:24,111][Thread-90:19360][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:32:43,035][Thread-92:26112][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:33:13,041][Thread-94:20956][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:33:23,222][Thread-96:25816][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:33:33,175][Thread-98:20692][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:33:43,041][Thread-100:24972][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:33:53,146][Thread-102:17876][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:34:03,589][Thread-104:17716][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:34:13,155][Thread-106:26536][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:34:23,307][Thread-108:25260][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:34:33,120][Thread-110:23660][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:34:53,247][Thread-112:26196][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:35:03,241][Thread-114:23604][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:35:24,317][Thread-117:23708][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:35:44,995][Thread-119:21148][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:35:54,319][Thread-121:20532][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:36:14,297][Thread-123:25060][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:36:24,346][Thread-125:16308][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:36:54,858][Thread-127:13976][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:37:05,070][Thread-129:12464][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:37:14,693][Thread-131:17952][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:37:24,757][Thread-133:18660][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:37:34,458][Thread-135:23836][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:37:44,323][Thread-137:16892][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:38:14,356][Thread-139:6056][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:38:44,499][Thread-141:13340][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:38:59,696][Thread-143:20416][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:39:30,086][Thread-145:21960][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:39:39,730][Thread-147:18912][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:39:59,774][Thread-149:1640][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:40:19,219][Thread-151:9404][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:40:43,723][Thread-153:25908][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:40:53,614][Thread-155:23148][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:41:09,346][Thread-157:24224][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:41:30,036][Thread-159:22776][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:41:49,344][Thread-161:22100][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:41:55,301][MainThread:26120][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-30 11:41:55,874][MainThread:24684][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 11:42:09,672][Thread-2:25340][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:42:19,373][Thread-4:21400][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:42:29,389][Thread-6:24608][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:42:39,307][Thread-8:20932][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:43:04,580][Thread-10:26308][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:43:14,609][Thread-12:14016][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:43:19,159][MainThread:24684][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-30 11:43:19,657][MainThread:20760][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 11:43:23,606][MainThread:20760][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-30 11:43:24,265][MainThread:25356][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 11:43:34,736][Thread-2:22664][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:43:44,617][Thread-4:22604][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:44:03,324][MainThread:25356][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-30 11:44:04,085][MainThread:24144][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 11:44:14,273][Thread-2:26440][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:44:24,329][Thread-4:16780][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:45:55,221][MainThread:21952][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 11:46:04,263][Thread-2:25120][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:46:14,687][Thread-4:25368][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:46:24,376][Thread-6:13324][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:46:34,297][Thread-8:19940][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:46:44,266][Thread-10:7544][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:46:54,283][Thread-12:18704][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:47:04,323][Thread-14:26340][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:47:14,459][Thread-16:25444][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:47:24,446][Thread-18:18676][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:47:34,321][Thread-20:25844][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:47:54,274][Thread-22:16936][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:48:05,462][Thread-24:15696][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:48:14,665][Thread-26:19784][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:48:24,300][Thread-28:20084][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:48:44,331][Thread-30:7580][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:48:54,614][Thread-32:26060][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:48:59,573][MainThread:21952][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-30 11:49:00,368][MainThread:23608][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 11:49:04,493][Thread-2:13452][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:49:24,711][MainThread:23608][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\AutoTestCode\urls.py changed, reloading.]
[2023-06-30 11:49:25,290][MainThread:25892][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 11:49:34,396][Thread-2:19680][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:49:44,733][Thread-4:23496][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:50:14,445][Thread-6:10908][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:50:24,775][Thread-8:15464][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:50:34,371][Thread-10:900][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:50:38,102][MainThread:25892][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-30 11:50:38,635][MainThread:24028][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 11:50:44,365][Thread-2:23108][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:50:44,939][MainThread:24028][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-30 11:50:45,471][MainThread:23632][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 11:50:54,379][Thread-2:26224][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:51:22,233][Thread-4:25972][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:51:32,049][Thread-6:16452][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:51:35,770][Thread-7:9736][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:51:41,909][Thread-9:6264][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:51:45,638][Thread-7:9736][task_id:django.request][log.py:241][WARNING][Not Found: /api/config/]
[2023-06-30 11:51:51,930][Thread-11:21524][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:52:02,071][Thread-13:20744][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:52:02,606][MainThread:23632][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\AutoTestCode\urls.py changed, reloading.]
[2023-06-30 11:52:03,171][MainThread:12744][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 11:52:05,756][Thread-1:12464][task_id:django.request][log.py:241][WARNING][Not Found: /api/config/]
[2023-06-30 11:52:18,877][MainThread:12744][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\AutoTestCode\urls.py changed, reloading.]
[2023-06-30 11:52:19,505][MainThread:21972][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 11:52:21,155][Thread-1:23184][task_id:django.request][log.py:241][ERROR][Internal Server Error: /api/config/]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view FacebookScreenshot.views.test didn't return an HttpResponse object. It returned None instead.
[2023-06-30 11:52:21,155][Thread-1:23184][task_id:django.request][log.py:241][ERROR][Internal Server Error: /api/config/]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view FacebookScreenshot.views.test didn't return an HttpResponse object. It returned None instead.
[2023-06-30 11:52:32,581][Thread-3:18788][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:52:42,267][Thread-5:25952][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:52:45,742][Thread-1:23184][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:52:52,312][Thread-7:19828][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 11:52:52,427][MainThread:21972][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\AutoTestCode\urls.py changed, reloading.]
[2023-06-30 11:52:53,013][MainThread:22932][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 11:52:56,390][Thread-1:19728][task_id:django.request][log.py:241][ERROR][Internal Server Error: /api/config]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 29, in test
    print(request.meta.get("remote_addr"))
AttributeError: 'WSGIRequest' object has no attribute 'meta'
[2023-06-30 11:52:56,390][Thread-1:19728][task_id:django.request][log.py:241][ERROR][Internal Server Error: /api/config]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 29, in test
    print(request.meta.get("remote_addr"))
AttributeError: 'WSGIRequest' object has no attribute 'meta'
[2023-06-30 11:53:02,308][Thread-3:12828][task_id:django.request][log.py:241][ERROR][Internal Server Error: /api/config]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 29, in test
    print(request.meta.get("remote_addr"))
AttributeError: 'WSGIRequest' object has no attribute 'meta'
[2023-06-30 11:53:02,308][Thread-3:12828][task_id:django.request][log.py:241][ERROR][Internal Server Error: /api/config]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 29, in test
    print(request.meta.get("remote_addr"))
AttributeError: 'WSGIRequest' object has no attribute 'meta'
[2023-06-30 11:53:17,471][MainThread:22932][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-30 11:53:18,025][MainThread:21196][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 11:53:21,553][Thread-1:18436][task_id:django.request][log.py:241][ERROR][Internal Server Error: /api/config]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 29, in test
    print(request.Meta.get("remote_addr"))
AttributeError: 'WSGIRequest' object has no attribute 'Meta'
[2023-06-30 11:53:21,553][Thread-1:18436][task_id:django.request][log.py:241][ERROR][Internal Server Error: /api/config]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 29, in test
    print(request.Meta.get("remote_addr"))
AttributeError: 'WSGIRequest' object has no attribute 'Meta'
[2023-06-30 11:53:52,025][Thread-3:19560][task_id:django.request][log.py:241][ERROR][Internal Server Error: /api/config]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 29, in test
    print(request.Meta.get("remote_addr"))
AttributeError: 'WSGIRequest' object has no attribute 'Meta'
[2023-06-30 11:53:52,025][Thread-3:19560][task_id:django.request][log.py:241][ERROR][Internal Server Error: /api/config]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 29, in test
    print(request.Meta.get("remote_addr"))
AttributeError: 'WSGIRequest' object has no attribute 'Meta'
[2023-06-30 11:54:02,019][Thread-5:17708][task_id:django.request][log.py:241][ERROR][Internal Server Error: /api/config]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 29, in test
    print(request.Meta.get("remote_addr"))
AttributeError: 'WSGIRequest' object has no attribute 'Meta'
[2023-06-30 11:54:02,019][Thread-5:17708][task_id:django.request][log.py:241][ERROR][Internal Server Error: /api/config]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 29, in test
    print(request.Meta.get("remote_addr"))
AttributeError: 'WSGIRequest' object has no attribute 'Meta'
[2023-06-30 11:54:12,166][Thread-7:6208][task_id:django.request][log.py:241][ERROR][Internal Server Error: /api/config]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 29, in test
    print(request.Meta.get("remote_addr"))
AttributeError: 'WSGIRequest' object has no attribute 'Meta'
[2023-06-30 11:54:12,166][Thread-7:6208][task_id:django.request][log.py:241][ERROR][Internal Server Error: /api/config]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 29, in test
    print(request.Meta.get("remote_addr"))
AttributeError: 'WSGIRequest' object has no attribute 'Meta'
[2023-06-30 11:54:20,932][MainThread:21196][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-30 11:54:21,537][MainThread:8704][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 11:54:50,259][MainThread:8704][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-30 11:54:50,832][MainThread:24052][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 14:15:53,574][MainThread:22128][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 14:29:21,923][MainThread:22128][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\AutoTestCode\urls.py changed, reloading.]
[2023-06-30 14:29:22,469][MainThread:24768][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 14:29:35,509][Thread-2:25440][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:29:45,164][Thread-4:14880][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:29:55,321][Thread-6:13664][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:30:06,246][Thread-8:21376][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:30:15,187][Thread-10:18656][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:30:26,395][Thread-12:25008][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:30:46,784][Thread-14:23476][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:31:25,640][Thread-16:22552][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:31:35,531][Thread-18:23952][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:31:45,256][Thread-20:23848][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:31:57,599][Thread-22:25744][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:32:05,387][Thread-24:18536][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:32:35,687][Thread-26:18944][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:32:45,350][Thread-28:14460][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:32:55,364][Thread-30:26116][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:33:15,374][Thread-32:26424][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:33:35,853][Thread-34:22260][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:33:55,426][Thread-36:23828][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:34:06,332][Thread-38:21164][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:34:15,564][Thread-40:22600][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:34:25,303][Thread-42:10980][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:34:45,473][Thread-44:18436][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:34:55,325][Thread-46:15012][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:35:05,470][Thread-48:24552][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:35:15,403][Thread-50:23924][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:35:25,476][Thread-52:17452][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:35:35,332][Thread-54:24704][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:35:45,468][Thread-56:2656][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:35:55,322][Thread-58:22412][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:36:15,391][Thread-60:18356][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:36:25,491][Thread-63:21840][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:36:45,420][Thread-66:25404][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:36:55,486][Thread-68:26152][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:37:05,508][Thread-70:18800][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:37:15,553][Thread-72:16252][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:37:25,702][Thread-74:19392][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:37:55,416][Thread-76:21532][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:38:15,500][Thread-78:24060][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:38:25,491][Thread-80:17052][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:38:35,459][Thread-82:3036][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:38:45,411][Thread-84:6232][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:39:05,527][Thread-86:14952][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:39:19,977][MainThread:24768][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-30 14:39:20,562][MainThread:25924][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 14:39:36,695][Thread-2:3708][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:39:55,454][Thread-4:23676][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:40:15,580][Thread-6:22244][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:40:25,632][Thread-8:16180][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:40:35,521][Thread-10:20476][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:40:45,617][Thread-12:22128][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:40:55,575][Thread-14:6208][task_id:django.request][log.py:241][WARNING][Not Found: /api/config]
[2023-06-30 14:41:25,913][MainThread:19360][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 15:05:42,007][MainThread:19360][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-30 15:05:42,780][MainThread:26600][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 15:26:12,620][Thread-1:26288][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 20, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 52, in screenshot
    while await page.locator("a", has_text="了解更多").is_visible(timeout=3000) is False:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17082, in is_visible
    return mapping.from_maybe_impl(await self._impl_obj.is_visible(timeout=timeout))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 492, in is_visible
    return await self._frame.is_visible(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 353, in is_visible
    return await self._channel.send("isVisible", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
[2023-06-30 15:26:12,620][Thread-1:26288][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 20, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 52, in screenshot
    while await page.locator("a", has_text="了解更多").is_visible(timeout=3000) is False:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17082, in is_visible
    return mapping.from_maybe_impl(await self._impl_obj.is_visible(timeout=timeout))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 492, in is_visible
    return await self._frame.is_visible(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 353, in is_visible
    return await self._channel.send("isVisible", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
[2023-06-30 15:27:02,514][MainThread:26600][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-30 15:27:03,071][MainThread:26412][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 15:27:36,588][MainThread:26412][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-30 15:27:37,503][MainThread:19028][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 15:41:10,189][MainThread:19028][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-30 15:41:11,342][MainThread:19380][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 15:42:24,469][MainThread:19380][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-30 15:42:25,594][MainThread:17876][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 15:43:48,554][MainThread:17876][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-30 15:43:49,725][MainThread:21708][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 15:43:54,914][MainThread:21708][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-30 15:43:56,032][MainThread:18956][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 15:46:10,085][Thread-3:22552][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 20, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 52, in screenshot
    while await page.locator("a", has_text="了解更多").is_visible(timeout=3000) is False:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17082, in is_visible
    return mapping.from_maybe_impl(await self._impl_obj.is_visible(timeout=timeout))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 492, in is_visible
    return await self._frame.is_visible(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 353, in is_visible
    return await self._channel.send("isVisible", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
[2023-06-30 15:46:10,085][Thread-3:22552][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 20, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 52, in screenshot
    while await page.locator("a", has_text="了解更多").is_visible(timeout=3000) is False:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17082, in is_visible
    return mapping.from_maybe_impl(await self._impl_obj.is_visible(timeout=timeout))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 492, in is_visible
    return await self._frame.is_visible(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 353, in is_visible
    return await self._channel.send("isVisible", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
[2023-06-30 15:48:05,536][Thread-7:14352][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 20, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 53, in screenshot
    await page.mouse.wheel(0, 500)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 1519, in wheel
    await self._impl_obj.wheel(deltaX=delta_x, deltaY=delta_y)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_input.py", line 84, in wheel
    await self._channel.send("mouseWheel", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target closed
[2023-06-30 15:48:05,536][Thread-7:14352][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 20, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 53, in screenshot
    await page.mouse.wheel(0, 500)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 1519, in wheel
    await self._impl_obj.wheel(deltaX=delta_x, deltaY=delta_y)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_input.py", line 84, in wheel
    await self._channel.send("mouseWheel", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target closed
[2023-06-30 15:50:44,946][Thread-11:21168][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 20, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 64, in screenshot
    screenshot_bytes = await i.screenshot()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17240, in screenshot
    await self._impl_obj.screenshot(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 521, in screenshot
    return await self._with_element(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 119, in _with_element
    return await task(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_element_handle.py", line 306, in screenshot
    encoded_binary = await self._channel.send("screenshot", params)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 29735ms exceeded.
=========================== logs ===========================
taking element screenshot
  waiting for element to be visible and stable
  element is visible and stable
============================================================
[2023-06-30 15:50:44,946][Thread-11:21168][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 20, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 64, in screenshot
    screenshot_bytes = await i.screenshot()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17240, in screenshot
    await self._impl_obj.screenshot(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 521, in screenshot
    return await self._with_element(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 119, in _with_element
    return await task(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_element_handle.py", line 306, in screenshot
    encoded_binary = await self._channel.send("screenshot", params)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 29735ms exceeded.
=========================== logs ===========================
taking element screenshot
  waiting for element to be visible and stable
  element is visible and stable
============================================================
[2023-06-30 16:00:43,945][MainThread:18956][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-30 16:00:44,751][MainThread:6944][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 16:01:10,162][MainThread:6944][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-30 16:01:11,005][MainThread:17944][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 16:09:35,531][MainThread:17944][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-30 16:09:36,424][MainThread:1528][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 16:14:05,526][MainThread:1528][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-30 16:14:06,472][MainThread:23216][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 16:16:26,133][MainThread:23216][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-30 16:16:26,849][MainThread:23108][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 16:19:02,161][MainThread:23108][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-30 16:19:03,029][MainThread:11644][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 16:59:56,693][MainThread:11644][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-30 16:59:57,576][MainThread:4180][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 17:01:56,472][MainThread:4180][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-30 17:01:57,408][MainThread:12248][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 17:07:29,965][MainThread:12248][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-30 17:07:30,739][MainThread:26148][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 17:18:23,170][MainThread:26148][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-30 17:18:24,029][MainThread:19216][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 17:25:49,693][MainThread:19216][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-30 17:25:50,679][MainThread:22016][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 17:32:37,921][MainThread:22016][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-30 17:32:39,177][MainThread:20356][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 17:32:44,550][MainThread:20356][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-30 17:32:45,923][MainThread:25788][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 17:38:22,347][MainThread:25788][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-30 17:38:23,495][MainThread:25952][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 17:38:49,219][MainThread:25952][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-30 17:38:50,010][MainThread:23788][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 17:42:00,833][MainThread:23788][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-30 17:42:01,556][MainThread:20080][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 17:45:13,762][Thread-2:9692][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 20, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 75, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 64, in screenshot
    screenshot_bytes = await i.screenshot()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17240, in screenshot
    await self._impl_obj.screenshot(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 521, in screenshot
    return await self._with_element(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 115, in _with_element
    handle = await self.element_handle(timeout=timeout)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 315, in element_handle
    handle = await self._frame.wait_for_selector(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 322, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target closed
=========================== logs ===========================
waiting for get_by_role("article").filter(has_text=re.compile(r".*CO659F5A.*")).nth(3)
============================================================
[2023-06-30 17:45:13,762][Thread-2:9692][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 20, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 75, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 64, in screenshot
    screenshot_bytes = await i.screenshot()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17240, in screenshot
    await self._impl_obj.screenshot(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 521, in screenshot
    return await self._with_element(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 115, in _with_element
    handle = await self.element_handle(timeout=timeout)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 315, in element_handle
    handle = await self._frame.wait_for_selector(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 322, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target closed
=========================== logs ===========================
waiting for get_by_role("article").filter(has_text=re.compile(r".*CO659F5A.*")).nth(3)
============================================================
[2023-06-30 17:45:13,775][Thread-4:3752][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 20, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 75, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 45, in screenshot
    if await page.get_by_text("展开").count() > 0:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 16661, in count
    return mapping.from_maybe_impl(await self._impl_obj.count())
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 384, in count
    return await self._frame._query_count(self._selector)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 131, in _query_count
    return await self._channel.send("queryCount", {"selector": selector})
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
[2023-06-30 17:45:13,775][Thread-4:3752][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 20, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 75, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 45, in screenshot
    if await page.get_by_text("展开").count() > 0:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 16661, in count
    return mapping.from_maybe_impl(await self._impl_obj.count())
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 384, in count
    return await self._frame._query_count(self._selector)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 131, in _query_count
    return await self._channel.send("queryCount", {"selector": selector})
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
[2023-06-30 17:45:24,188][MainThread:20080][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-30 17:45:24,945][MainThread:20484][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 17:47:33,404][Thread-2:20300][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 20, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 75, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 45, in screenshot
    if await page.get_by_text("展开").count() > 0:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 16661, in count
    return mapping.from_maybe_impl(await self._impl_obj.count())
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 384, in count
    return await self._frame._query_count(self._selector)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 131, in _query_count
    return await self._channel.send("queryCount", {"selector": selector})
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
[2023-06-30 17:47:33,404][Thread-2:20300][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 20, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 75, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 45, in screenshot
    if await page.get_by_text("展开").count() > 0:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 16661, in count
    return mapping.from_maybe_impl(await self._impl_obj.count())
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 384, in count
    return await self._frame._query_count(self._selector)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 131, in _query_count
    return await self._channel.send("queryCount", {"selector": selector})
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
[2023-06-30 17:49:23,754][Thread-5:7800][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 20, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 75, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 52, in screenshot
    while await page.locator("a", has_text="了解更多").is_visible(timeout=3000) is False:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17082, in is_visible
    return mapping.from_maybe_impl(await self._impl_obj.is_visible(timeout=timeout))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 492, in is_visible
    return await self._frame.is_visible(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 353, in is_visible
    return await self._channel.send("isVisible", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
[2023-06-30 17:49:23,754][Thread-5:7800][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 20, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 75, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 52, in screenshot
    while await page.locator("a", has_text="了解更多").is_visible(timeout=3000) is False:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17082, in is_visible
    return mapping.from_maybe_impl(await self._impl_obj.is_visible(timeout=timeout))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 492, in is_visible
    return await self._frame.is_visible(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 353, in is_visible
    return await self._channel.send("isVisible", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
[2023-06-30 17:49:59,427][Thread-6:23584][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 20, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 75, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 45, in screenshot
    if await page.get_by_text("展开").count() > 0:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 16661, in count
    return mapping.from_maybe_impl(await self._impl_obj.count())
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 384, in count
    return await self._frame._query_count(self._selector)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 131, in _query_count
    return await self._channel.send("queryCount", {"selector": selector})
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
[2023-06-30 17:49:59,427][Thread-6:23584][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 20, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 75, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 45, in screenshot
    if await page.get_by_text("展开").count() > 0:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 16661, in count
    return mapping.from_maybe_impl(await self._impl_obj.count())
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 384, in count
    return await self._frame._query_count(self._selector)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 131, in _query_count
    return await self._channel.send("queryCount", {"selector": selector})
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
[2023-06-30 17:51:09,159][Thread-9:26416][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 20, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 75, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 45, in screenshot
    if await page.get_by_text("展开").count() > 0:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 16661, in count
    return mapping.from_maybe_impl(await self._impl_obj.count())
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 384, in count
    return await self._frame._query_count(self._selector)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 131, in _query_count
    return await self._channel.send("queryCount", {"selector": selector})
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
[2023-06-30 17:51:09,159][Thread-9:26416][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 20, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 75, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 45, in screenshot
    if await page.get_by_text("展开").count() > 0:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 16661, in count
    return mapping.from_maybe_impl(await self._impl_obj.count())
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 384, in count
    return await self._frame._query_count(self._selector)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 131, in _query_count
    return await self._channel.send("queryCount", {"selector": selector})
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
[2023-06-30 17:51:20,088][Thread-10:23992][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 20, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 75, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 45, in screenshot
    if await page.get_by_text("展开").count() > 0:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 16661, in count
    return mapping.from_maybe_impl(await self._impl_obj.count())
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 384, in count
    return await self._frame._query_count(self._selector)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 131, in _query_count
    return await self._channel.send("queryCount", {"selector": selector})
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
[2023-06-30 17:51:20,088][Thread-10:23992][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 20, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 75, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 45, in screenshot
    if await page.get_by_text("展开").count() > 0:
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 16661, in count
    return mapping.from_maybe_impl(await self._impl_obj.count())
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 384, in count
    return await self._frame._query_count(self._selector)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 131, in _query_count
    return await self._channel.send("queryCount", {"selector": selector})
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
[2023-06-30 17:54:21,856][MainThread:25008][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-30 17:58:19,677][MainThread:25008][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-30 17:58:20,392][MainThread:28404][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-07-03 09:35:22,479][Thread-1:27612][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 20, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 74, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}', wait_until="domcontentloaded")
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: net::ERR_PROXY_CONNECTION_FAILED at https://www.facebook.com/search/top/?q=75J7RQFX
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "domcontentloaded"
============================================================
[2023-07-03 09:35:22,479][Thread-1:27612][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 20, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 74, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}', wait_until="domcontentloaded")
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: net::ERR_PROXY_CONNECTION_FAILED at https://www.facebook.com/search/top/?q=75J7RQFX
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "domcontentloaded"
============================================================
[2023-07-03 09:35:34,027][Thread-3:26584][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 20, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 74, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}', wait_until="domcontentloaded")
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: net::ERR_PROXY_CONNECTION_FAILED at https://www.facebook.com/search/top/?q=75J7RQFX
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "domcontentloaded"
============================================================
[2023-07-03 09:35:34,027][Thread-3:26584][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 20, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 74, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 38, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}', wait_until="domcontentloaded")
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: net::ERR_PROXY_CONNECTION_FAILED at https://www.facebook.com/search/top/?q=75J7RQFX
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "domcontentloaded"
============================================================
[2023-07-03 09:37:25,285][MainThread:28404][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
